# Generated by Django 5.0.1 on 2026-09-19 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0048_team_old_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBotStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nome da Estratégia (ex: Sniper de Gol no Final)', max_length=150)),
                ('telegram_chat_id', models.CharField(help_text='Chat ID ou @username do Telegram', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('min_minute', models.IntegerField(default=70, help_text='Minuto mínimo da partida')),
                ('max_minute', models.IntegerField(default=85, help_text='Minuto máximo da partida')),
                ('score_condition', models.CharField(choices=[('any', 'Qualquer Placar'), ('draw', 'Apenas Jogos Empatados (0x0, 1x1, 2x2)'), ('home_losing_1', 'Mandante Perdendo por 1 Gol'), ('away_losing_1', 'Visitante Perdendo por 1 Gol'), ('fav_losing', 'Favorito Pré-Jogo Perdendo')], default='any', max_length=25)),
                ('max_total_goals', models.IntegerField(blank=True, help_text='Máximo de gols na partida (ex: 2 para jogos Under)', null=True)),
                ('min_pressure_5m', models.IntegerField(default=60, help_text='Pressão mínima nos últimos 5 min (%)')),
                ('min_total_corners', models.IntegerField(default=0, help_text='Mínimo de escanteios totais')),
                ('min_total_shots', models.IntegerField(default=0, help_text='Mínimo de finalizações totais')),
                ('min_shots_per_minute', models.FloatField(default=0.0, help_text='Ritmo mínimo de finalizações por minuto (APM)')),
                ('market_suggestion', models.CharField(default='Over Gols Limite', help_text='Sugestão de entrada (ex: Over 0.5 FT, Over Cantos)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_alerts_sent', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBotAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute_sent', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_alert_logs', to='matches.match')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='matches.userbotstrategy')),
            ],
            options={
                'unique_together': {('strategy', 'match')},
            },
        ),
    ]
